// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Authentication user",
                "responses": {
                    "200": {
                        "description": "result and token",
                        "schema": {
                            "$ref": "#/definitions/Default"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register user with data. ATTENTION! Password must be \u003e=6 symbols",
                "produces": [
                    "application/json"
                ],
                "summary": "Register user with specified model",
                "responses": {
                    "200": {
                        "description": "result and token",
                        "schema": {
                            "$ref": "#/definitions/Default"
                        }
                    }
                }
            }
        },
        "/user/{userUUID}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Deleting user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user uuid from token",
                        "name": "userUUID",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/user/{userUUID}/info": {
            "get": {
                "description": "Getting user's profile info",
                "produces": [
                    "application/json"
                ],
                "summary": "Getting user's profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user uuid from token",
                        "name": "userUUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user info",
                        "schema": {
                            "$ref": "#/definitions/Default"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Default": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "object"
                },
                "result": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "MicroWorld Swagger API",
	Description: "Swagger API for microworld project",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
